/*
  All the words and sample data the portal shows, in one place.
  Views read from Portal.content instead of typing text inline, so wording
  can be changed here without touching any logic.
*/
window.Portal = window.Portal || {};

Portal.content = {
  app: {
    name: "UTC Student Services",
    mark: "UTC",
    skip: "Skip to main content",
    demoNotice: "Demo mode: what you enter is saved in this browser only. Nothing is sent to a server.",
    serverNotice: "Your entries are saved on the server. There is no login yet, so they are tied to this browser.",
    requestFailed: "That did not go through. Please try again.",
    loading: "Loading your portal...",
    servedBy: "Served by",
    localPreview: "Local preview (no server)",
    reset: "Clear my data",
    resetConfirm: "Clear everything you entered, including uploaded files? This cannot be undone.",
    resetDone: "Your data was cleared.",
    navLabel: "Main",
  },

  nav: [
    { id: "dashboard", label: "Dashboard", icon: "home" },
    { id: "enrollment", label: "Enrollment", icon: "check" },
    { id: "documents", label: "Documents", icon: "file" },
    { id: "labs", label: "Lab access", icon: "flask" },
    { id: "support", label: "Support", icon: "help" },
    { id: "courses", label: "Courses", icon: "book" },
  ],

  status: {
    done: "Done",
    current: "Next step",
    todo: "Not started",
    pending: "Pending review",
    open: "Open",
    withdrawn: "Withdrawn",
    cancelled: "Cancelled",
    received: "Received",
    missing: "Missing",
    planned: "In your plan",
  },

  dashboard: {
    title: "Welcome back",
    subtitle: "Here is where things stand and what to do next.",
    statusEyebrow: "Enrollment status",
    allDoneTitle: "You are ready for advisor review",
    allDoneBody: "Every step you control is complete. Staff will review your file.",
    nextPrefix: "Next: ",
    goToStep: "Go to this step",
    viewEnrollment: "View enrollment",
    stats: {
      documents: "Required documents",
      documentsHint: "received",
      courses: "Courses planned",
      creditsHint: "credits",
      labs: "Lab requests",
      labsHint: "pending review",
      tickets: "Support requests",
      ticketsHint: "open",
    },
    recentTitle: "Recent activity",
    recentEmpty: "Nothing yet. Activity shows up here as you use the portal.",
    quickTitle: "Quick actions",
    quick: [
      { label: "Upload a document", route: "documents" },
      { label: "Request lab access", route: "labs" },
      { label: "Open a support request", route: "support" },
      { label: "Browse courses", route: "courses" },
    ],
    activity: {
      document: "Uploaded",
      lab: "Requested lab access:",
      ticket: "Opened support request:",
    },
  },

  enrollment: {
    title: "Enrollment",
    subtitle: "Follow the steps in order. Each one updates by itself as you finish it.",
    stepsTitle: "Your steps",
    open: "Open",
    steps: {
      application: { label: "Application received", detail: "We have your application on file." },
      documents: { label: "Submit required documents", detail: "Upload each required document.", route: "documents" },
      courses: { label: "Choose your courses", detail: "Add at least one course to your plan.", route: "courses" },
      review: { label: "Advisor review", detail: "Staff check your file after the steps above are done." },
    },
    documentsProgress: " of ",
    documentsProgressEnd: " received",
    coursesProgress: " planned",
    reviewWaiting: "Waiting on the steps above",
    reviewReady: "Ready for staff",
  },

  documents: {
    title: "Documents",
    subtitle: "Send in the records the school needs from you.",
    requiredTitle: "Required documents",
    uploadTitle: "Upload a document",
    listTitle: "Your uploads",
    typeLabel: "Document type",
    fileLabel: "File",
    dropStrong: "Drop a file here or click to choose",
    dropHint: "PDF, JPG or PNG, up to 10 MB",
    selected: "Selected: ",
    submit: "Upload document",
    remove: "Remove",
    empty: "No documents uploaded yet.",
    demoNote: "Demo: the file stays on your device. Only its name, type and size are remembered.",
    serverNote: "Your file is stored privately and only you can download it.",
    download: "Download",
    errors: {
      noFile: "Choose a file first.",
      badType: "That file type is not accepted. Use PDF, JPG or PNG.",
      tooBig: "That file is larger than 10 MB.",
    },
    added: "Document received.",
    removed: "Document removed.",
    maxBytes: 10 * 1024 * 1024,
    accept: ".pdf,.jpg,.jpeg,.png",
    acceptedMime: ["application/pdf", "image/jpeg", "image/png"],
    types: [
      { id: "photo-id", label: "Photo ID", required: true },
      { id: "transcript", label: "Official transcript", required: true },
      { id: "immunization", label: "Immunization record", required: true },
      { id: "other", label: "Other document", required: false },
    ],
  },

  labs: {
    title: "Lab access",
    subtitle: "Ask for time in a lab. Staff approve each request.",
    formTitle: "New request",
    listTitle: "Your requests",
    labLabel: "Lab",
    dateLabel: "Date",
    slotLabel: "Time slot",
    reasonLabel: "What will you work on?",
    reasonHint: "A sentence or two is enough.",
    submit: "Request access",
    cancel: "Cancel request",
    empty: "No lab requests yet.",
    added: "Lab request sent.",
    cancelled: "Lab request cancelled.",
    errors: { reason: "Tell us briefly what you will work on (at least 10 characters).", date: "Pick a date that is today or later." },
    labs: [
      { id: "cloud", label: "Cloud Computing Lab (Room 210)" },
      { id: "network", label: "Networking Lab (Room 114)" },
      { id: "security", label: "Cybersecurity Lab (Room 305)" },
      { id: "open", label: "Open Computer Lab (Library)" },
    ],
    slots: ["9:00 AM - 11:00 AM", "11:00 AM - 1:00 PM", "1:00 PM - 3:00 PM", "3:00 PM - 5:00 PM", "6:00 PM - 8:00 PM"],
  },

  support: {
    title: "Support",
    subtitle: "Stuck on something? Open a request and track it here.",
    formTitle: "New request",
    listTitle: "Your requests",
    categoryLabel: "Category",
    priorityLabel: "Priority",
    subjectLabel: "Subject",
    detailsLabel: "Details",
    detailsHint: "What happened, and what did you expect?",
    submit: "Open request",
    withdraw: "Withdraw",
    empty: "No support requests yet.",
    added: "Support request opened: ",
    withdrawn: "Request withdrawn.",
    errors: { subject: "Add a short subject (at least 4 characters).", details: "Add a few details (at least 10 characters)." },
    categories: ["Account and login", "Enrollment", "Documents", "Lab access", "Courses", "Something else"],
    priorities: ["Normal", "High"],
  },

  courses: {
    title: "Courses",
    subtitle: "Browse this term's courses and build your plan.",
    searchLabel: "Search courses",
    searchPlaceholder: "Title, code or instructor",
    deptLabel: "Department",
    allDepts: "All departments",
    add: "Add to plan",
    remove: "Remove from plan",
    credits: " credits",
    planSummary: "Your plan: ",
    planCourses: " courses, ",
    empty: "No courses match your search.",
    added: "Added to your plan.",
    removed: "Removed from your plan.",
    overLimit: "That would go over the 18 credit limit.",
    maxCredits: 18,
    catalog: [
      { id: "cld101", code: "CLD 101", title: "Introduction to Cloud Computing", dept: "Cloud", instructor: "Dr. A. Mensah", schedule: "Mon / Wed 9:00 AM", location: "Room 210", credits: 3 },
      { id: "cld220", code: "CLD 220", title: "Infrastructure as Code", dept: "Cloud", instructor: "Prof. L. Ortiz", schedule: "Tue / Thu 1:00 PM", location: "Room 210", credits: 4 },
      { id: "cld310", code: "CLD 310", title: "Highly Available Architectures", dept: "Cloud", instructor: "Dr. A. Mensah", schedule: "Fri 10:00 AM", location: "Room 212", credits: 3 },
      { id: "net150", code: "NET 150", title: "Networking Fundamentals", dept: "Networking", instructor: "Prof. R. Okafor", schedule: "Mon / Wed 1:00 PM", location: "Room 114", credits: 3 },
      { id: "net260", code: "NET 260", title: "Routing and Load Balancing", dept: "Networking", instructor: "Prof. R. Okafor", schedule: "Tue / Thu 9:00 AM", location: "Room 114", credits: 3 },
      { id: "sec200", code: "SEC 200", title: "Security Essentials", dept: "Security", instructor: "Dr. M. Haddad", schedule: "Tue / Thu 3:00 PM", location: "Room 305", credits: 3 },
      { id: "sec330", code: "SEC 330", title: "Identity and Access Management", dept: "Security", instructor: "Dr. M. Haddad", schedule: "Wed 6:00 PM", location: "Room 305", credits: 3 },
      { id: "dba240", code: "DBA 240", title: "Relational Databases", dept: "Data", instructor: "Prof. S. Nguyen", schedule: "Mon / Wed 3:00 PM", location: "Room 118", credits: 4 },
      { id: "ops280", code: "OPS 280", title: "Monitoring and Operations", dept: "Operations", instructor: "Prof. J. Baptiste", schedule: "Thu 6:00 PM", location: "Room 212", credits: 2 },
    ],
  },
};
